#!/usr/local/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers.

let request = require("request");
let url = process.argv[2];

const jsdom = require("jsdom");
const { JSDOM } = jsdom;
// if the number of argument is less than 1, exit with a usage statement.
if (process.argv.length < 3) {
  console.log("usage: wikp <url>");
} else {
  request(url, function (error, response, body) {
    // Simulate a Document Object Model.
    let { document } = (new JSDOM(body)).window;

    // Grab all the paragraphs and references.
    let paragraphs = document.querySelectorAll("p");
    let references = document.querySelectorAll(".reference");

    // Remove any references.
    references.forEach(reference => {
      reference.remove();
    });

    // Print out all of the paragraphs.
    paragraphs.forEach(paragraph => {
      console.log(paragraph.textContent);
    });
  });

}

